USE [Baseball]
GO

/****** Object:  Table [dbo].[baseball_stats]    Script Date: 11/25/2016 8:56:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO

CREATE EXTERNAL TABLE [dbo].[baseball_stats]
(
	[game_id] [varchar](150) NULL,
	[visiting_team] [varchar](10) NULL,
	[inning] [varchar](5) NULL,
	[batting_team] [varchar](5) NULL,
	[outs] [varchar](5) NULL,
	[balls] [varchar](5) NULL,
	[strikes] [varchar](5) NULL,
	[pitch_seq] [varchar](100) NULL,
	[visitor_score] [varchar](5) NULL,
	[home_score] [varchar](5) NULL,
	[batter] [varchar](150) NULL,
	[batter_hand] [varchar](10) NULL,
	[res_batter] [varchar](150) NULL,
	[res_batter_hand] [varchar](10) NULL,
	[pitcher] [varchar](150) NULL,
	[pitcher_hand] [varchar](10) NULL,
	[res_pitcher] [varchar](150) NULL,
	[res_pitcher_hand] [varchar](10) NULL,
	[catcher] [varchar](150) NULL,
	[first_base] [varchar](150) NULL,
	[second_base] [varchar](150) NULL,
	[third_base] [varchar](150) NULL,
	[shortstop] [varchar](150) NULL,
	[left_field] [varchar](150) NULL,
	[center_field] [varchar](150) NULL,
	[right_field] [varchar](150) NULL,
	[first_runner] [varchar](150) NULL,
	[second_runner] [varchar](150) NULL,
	[third_runner] [varchar](150) NULL,
	[event_text] [varchar](150) NULL,
	[leadoff_flag] [varchar](10) NULL,
	[pinchhit_flag] [varchar](10) NULL,
	[defensive_pos] [varchar](5) NULL,
	[lineup_pos] [varchar](5) NULL,
	[event_type] [varchar](5) NULL,
	[batter_event_flag] [varchar](10) NULL,
	[ab_flag] [varchar](10) NULL,
	[hit_value] [varchar](5) NULL,
	[sh_flag] [varchar](10) NULL,
	[sf_flag] [varchar](10) NULL,
	[outs_on_play] [varchar](5) NULL,
	[double_play_flag] [varchar](10) NULL,
	[triple_play_flag] [varchar](10) NULL,
	[rbi_on_play] [varchar](5) NULL,
	[wild_pitch_flag] [varchar](10) NULL,
	[passed_ball_flag] [varchar](10) NULL,
	[fielded_by_flag] [varchar](5) NULL,
	[batted_ball_type] [varchar](10) NULL,
	[bunt_flag] [varchar](10) NULL,
	[foul_flag] [varchar](10) NULL,
	[hit_location] [varchar](10) NULL,
	[num_errors] [varchar](5) NULL,
	[1st_error_player] [varchar](5) NULL,
	[1st_error_type] [varchar](10) NULL,
	[2nd_error_player] [varchar](5) NULL,
	[2nd_error_type] [varchar](10) NULL,
	[3rd_error_player] [varchar](5) NULL,
	[3rd_error_type] [varchar](10) NULL,
	[batter_dest] [varchar](5) NULL,
	[runner_1st_dest] [varchar](5) NULL,
	[runner_2nd_dest] [varchar](5) NULL,
	[runner_3rd_dest] [varchar](5) NULL,
	[play_on_batter] [varchar](100) NULL,
	[play_on_1st_runner] [varchar](100) NULL,
	[play_on_2nd_runner] [varchar](100) NULL,
	[play_on_3rd_runner] [varchar](100) NULL,
	[sb_for_1st_flag] [varchar](10) NULL,
	[sb_for_2nd_flag] [varchar](10) NULL,
	[sb_for_3rd_flag] [varchar](10) NULL,
	[cs_for_1st_flag] [varchar](10) NULL,
	[cs_for_2nd_flag] [varchar](10) NULL,
	[cs_for_3rd_flag] [varchar](10) NULL,
	[po_for_1st_flag] [varchar](10) NULL,
	[po_for_2nd_flag] [varchar](10) NULL,
	[po_for_3rd_flag] [varchar](10) NULL,
	[resp_pitcher_1st_runner] [varchar](150) NULL,
	[resp_pitcher_2nd_runner] [varchar](150) NULL,
	[resp_pitcher_3rd_runner] [varchar](150) NULL,
	[new_game_flag] [varchar](10) NULL,
	[end_game_flag] [varchar](10) NULL,
	[pinch_runner_on_1st] [varchar](150) NULL,
	[pinch_runner_on_2nd] [varchar](150) NULL,
	[pinch_runner_on_3rd] [varchar](150) NULL,
	[runner_removed_on_1st] [varchar](150) NULL,
	[runner_removed_on_2nd] [varchar](150) NULL,
	[runner_removed_on_3rd] [varchar](150) NULL,
	[batter_rem_pinch_batter] [varchar](150) NULL,
	[pos_batter_rem] [varchar](5) NULL,
	[fielder_w_1st_putout] [varchar](5) NULL,
	[fielder_w_2nd_putout] [varchar](5) NULL,
	[fielder_w_3rd_putout] [varchar](5) NULL,
	[fielder_w_1st_assist] [varchar](5) NULL,
	[fielder_w_2nd_assist] [varchar](5) NULL,
	[fielder_w_3rd_assist] [varchar](5) NULL,
	[fielder_w_4th_assist] [varchar](5) NULL,
	[fielder_w_5th_assist] [varchar](5) NULL,
	[event_num] [varchar](5) NULL
)
WITH (DATA_SOURCE = [PolyPgHadoop],LOCATION = N'/baseball_stats/',FILE_FORMAT = [CSV],REJECT_TYPE = VALUE,REJECT_VALUE = 0)

GO

